version: "3.7"
services:
  database:
    image: postgres:11.5

  app:
    image: ${IMAGE_TAG}
    entrypoint: sh -c
    env_file: ${ENVFILE}
    environment:
      STAGE: development
    volumes: [$VOLUMES]
    ports:
      - 3000:3000
    depends_on:
      - database