# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    parameters:
      ruby:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby >>
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps

  brakeman:
    parameters:
      ruby:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby >>
    steps:
      - checkout
      - run:
          command: gem install brakeman
      - run:
          command: brakeman -f plain -z --report-direct -w3

  test:
    parameters:
      ruby:
        type: string
      mongodb:
        type: string
      redis:
        type: string
    parallelism: 2
    docker:
      - image: cimg/ruby:<< parameters.ruby >>
        environment:
          - STAGE: test
          - MONGO_HOST: localhost
          - REDIS_HOST: localhost
      - image: mongo:<< parameters.mongodb >>
      - image: redis:<< parameters.redis >>

    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: "dockerize -wait tcp://localhost:27017 -timeout 1m"
          name: Wait for DB
      - run:
          command: "dockerize -wait tcp://localhost:6379 -timeout 1m"
          name: Wait for Redis
      - run:
          command: |
            shopt -s globstar
            mkdir -p /tmp/test-results/rspec
            TESTFILES=$(circleci tests glob spec/**/*_spec.rb | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
          name: Run rspec

      - store_artifacts:
          path: /tmp/test-results/rspec/results.xml

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              ruby: ["3.0"]
      - brakeman:
          matrix:
            parameters:
              ruby: ["3.0"]
          requires:
            - build
      - test:
          matrix:
            parameters:
              ruby: ["3.0"]
              mongodb: ["4.0", "4.2", "4.4"]
              redis: ["5.0", "6.0", "6.2"]
          requires:
            - build
