devel:
  database: rmud
  host: localhost
  username: rmud
  password: rmudrmud

production:
  database: rmud
  host: localhost
  username: root
  password: root

testing:
  database: rmud_testing
  host: localhost
  username: rmud
  password: rmudrmud