# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0]
        mongodb: [4.0, 4.2, 4.4]
        redis: [5.0, 6.0, 6.2]

    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }}, MongoDB ${{ matrix.mongodb }}
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        ports:
          - 27017:27017

      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Setup db, run tests
        env:
          STAGE: test
          MONGO_HOST: localhost
          REDIS_HOST: localhost
        run: |
          bundle exec rspec -f progress
